### ISSUE TITLE
Is flash attention really used?

### ISSUE THREAD

**Issue by ptits** [genmoai/models#10]
It causes error when installed from requirements.txt

**Comment by ved-genmo** [comment]
Can you try `uv pip install -e . --no-build-isolation`?

**Comment by cnielsen79** [comment]
Mine gets stuck at the same using uv pip install -e . --no-build-isolation

 
<img width="689" alt="Screenshot 2024-10-22 223635" src="https://github.com/user-attachments/assets/6313614d-7032-4fef-a915-3b87c95c9e4e">

**Comment by ved-genmo** [comment]
@cnielsen79 It probably takes a while to build flash attention. Possibly a half-hour or more.

**Comment by ptits** [comment]
> Can you try `uv pip install -e . --no-build-isolation`?

Collecting flash-attn>=2.6.3
  Using cached flash_attn-2.6.3.tar.gz (2.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-d8hsy1z4/flash-attn_7c0a9633585e4accace338e6cf252983/setup.py", line 160, in <module>
          raise RuntimeError(
      RuntimeError: FlashAttention is only supported on CUDA 11.6 and above.  Note: make sure nvcc has a supported version by running nvcc -V.


      torch.__version__  = 2.4.1+cu121


      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by dongyun-kim-arch** [comment]
Have the same error with CUDA version...
it would be great if docker environment is included in the repo...

**Comment by cnielsen79** [comment]
> @cnielsen79 It probably takes a while to build flash attention. Possibly a half-hour or more. Luckily, it should be a one time cost.

it never worked and gave up on it - seems like quite a few have this issue

**Comment by ved-genmo** [comment]
@cnielsen79 @ptits Flash attention is no longer necessary in the main branch of the repository. Try it out!
