### ISSUE TITLE
text encoders

### ISSUE THREAD

**Issue by ptits** [genmoai/models#13]
I dont see any code (inside this branch\fork) which download and store T5 model and encoders

May be i am dumb but please show me where (in which .py file) hf_hub_download or wget are used

I see T5_MODEL = "google/t5-v1_1-xxl"  and dont see how it is dowloaded with code

**Comment by Cascade42** [comment]
Just follow the chain of function calls.
The model is downloaded by T5Tokenizer.from_pretrained() / T5EncoderModel.from_pretrained() from the transformers library, which will then eventually download the model using the huggingface_hub library.
Check your site-packages if you want to see the code.
