### ISSUE TITLE
installation is not going through. 

### ISSUE THREAD

**Issue by selva221724** [genmoai/models#16]
```
uv pip install -e . --no-build-isolation
```
```
  × No solution found when resolving dependencies:
  ╰─▶ Because only the following versions of torch are available:
          torch<=2.4.1
          torch==2.5.0
      and torch>=2.4.1 has no wheels with a matching Python implementation tag, we can conclude that torch>=2.4.1,<2.5.0 cannot be used.
      And because mochi==0.1.0 depends on torch>=2.4.1, we can conclude that mochi==0.1.0 cannot be used.
      And because only mochi==0.1.0 is available and you require mochi, we can conclude that your requirements are unsatisfiable.
```

installation is not going through.

**Comment by mmtmn** [comment]
I just went with  pip install addict;pip install click;pip install einops;flash-pip install attn;pip install gradio;pip install omegaconf;pip install pillow;pip install pyyaml;pip install ray;pip install sentencepiece;pip install setuptools;pip install torch;pip install transformers;

and I'm using venv instead of uv - still waiting for the weights to finish downloading

**Comment by selva221724** [comment]
Great! Thanks @mmtmn , it went through! 
![539e6b1b14d803ff3e771265a8f9f7ad](https://github.com/user-attachments/assets/7121fea1-1045-4f61-ad08-b8e24f6c1d12)

**Comment by DZY-irene** [comment]
> I just went with `pip install addict;pip install click;pip install einops;flash-pip install attn;pip install gradio;pip install omegaconf;pip install pillow;pip install pyyaml;pip install ray;pip install sentencepiece;pip install setuptools;pip install torch;pip install transformers;`
> 
> and I'm using venv instead of uv - still waiting for the weights to finish downloading

Hello, I use the `conda create -n mochi python=3.10` and `pip install -r requirement.txt` but still failed to install flash-attn. May I ask how did you create the Mochi environment and what is your CUDA version? Thank you so much!

**Comment by sirajperson** [comment]
> pip install addict;pip install click;pip install einops;flash-pip install attn;pip install gradio;pip install omegaconf;pip install pillow;pip install pyyaml;pip install ray;pip install sentencepiece;pip install setuptools;pip install torch;pip install transformers;

I'm just saying that that is the best thank you I've ever seen. Thank you for thanking that way!
