### ISSUE TITLE
Releasing VAE Encoder

### ISSUE THREAD

**Issue by txytju** [genmoai/models#21]
Thanks for your release. Will VAE Encoder be released soon? VAE Encoder is needed for I2V training.

**Comment by akbar-genmo** [comment]
Thanks for you interest! Please see #9 for VAE encoder and #2 for I2V.

**Comment by EzioBy** [comment]
Thanks for your reply. Could you please provide an approximate timeline for the release of the VAE encoder?

**Comment by ajayjain** [comment]
The encoder is now merged and available for use. Weights are on our HuggingFace and here: https://x.com/genmoai/status/1852154518911304152
