### ISSUE TITLE
TypeError: AsymmetricAttention.__init__() got an unexpected keyword argument 'clip_feat_dim'

### ISSUE THREAD

**Issue by cene555** [genmoai/models#4]

**Comment by ved-genmo** [comment]
Hi! Thanks for trying out the inference repo. Can you provide the dit-config.yaml you used to run the model?

**Comment by rlsu9** [comment]
Hi, you can simple fix the error by deleting the unexpected keyworks from the dit-config.yaml. For me, I have deleted the `clip_feat_dim`, `pooled_caption_mlp_bias` and `use_transformer_engine` from dit-config.yaml and everything works fine. I guess its a mismatch between the ckpt on huggingface and the codebase.

**Comment by ved-genmo** [comment]
If you pull the latest version of this repository, this error should be gone @cene555.
