### ISSUE TITLE
Weights mismatch

### ISSUE THREAD

**Issue by ShafinH** [genmoai/models#46]
Downloaded weights from the hugging face [link](https://huggingface.co/genmo/mochi-1-preview/tree/main)

RuntimeError: Error(s) in loading state_dict for AsymmDiTJoint:
	Unexpected key(s) in state_dict: "t5_y_embedder.to_kv.bias", "t5_y_embedder.to_kv.weight", "t5_y_embedder.to_out.bias", "t5_y_embedder.to_out.weight", "t5_y_embedder.to_q.bias", "t5_y_embedder.to_q.weight", "t5_yproj.bias", "t5_yproj.weight".
	size mismatch for final_layer.linear.weight: copying a param with shape torch.Size([48, 3072]) from checkpoint, the shape in current model is torch.Size([96, 3072]).
	size mismatch for final_layer.linear.bias: copying a param with shape torch.Size([48]) from checkpoint, the shape in current model is torch.Size([96]).

**Comment by ved-genmo** [comment]
Can you try using the new download_weights script? Should reduce these types of errors.

**Comment by ShafinH** [comment]
Is there anyway to get the weights that were used when the infer.py file used to exist? I'm trying to run the version of the code on https://github.com/victorchall/genmoai-smol, but it seems like the code was refactored quite a bit recently.

**Comment by ved-genmo** [comment]
The official repository supports running on a single GPU now, so I'd recommend checking out the latest commit from this repo :)

Closing this, feel free to leave a comment if it's still not working.
