### ISSUE TITLE
Which Loss?

### ISSUE THREAD

**Issue by xesdiny** [genmoai/models#68]
SDE or ODE?

**Comment by ajayjain** [comment]
Hi @xesdiny,

We bundled an [Euler ODE sampler](https://github.com/genmoai/models/blob/1a96b5df0c83018fcbe7aebbbb1b34781e179921/src/genmo/mochi_preview/pipelines.py#L357-L369) into this repo. It's a deterministic sampler (the final video is a deterministic function of the initial noise, and no new noise is used during sampling).

An SDE solver that adds some extra noise during sampling would be an exciting topic to explore!
