### ISSUE TITLE
ideal number of frames

### ISSUE THREAD

**Issue by agneet42** [genmoai/models#69]
i was wondering what is the ideal number of frames that the model generates. specifically, what are the limits here : https://github.com/genmoai/models/blob/main/demos/api_example.py#L42 ?

**Comment by FurkanGozukara** [comment]
I did a huge tutorial and 121 frames and 40 steps works amazing with cfg 6

Here video tutorial : https://youtu.be/iqBV7bCbDJY

**Comment by akbar-genmo** [comment]
The model can generate images as well as videos. For videos, you can see this [issue](https://github.com/genmoai/models/issues/37#issuecomment-2451337657) on how to set number of frames. Note that the model might work best at generating 163 frame videos.
