### ISSUE TITLE
T5_MODEL = "google/t5-v1_1-xxl"

### ISSUE THREAD

**Issue by ptits** [genmoai/models#7]
should it be downloaded and stored somewhere?

**Comment by ved-genmo** [comment]
I believe huggingface will automatically download it for you.

**Comment by ptits** [comment]
I don't see code for downloading.

**Comment by ved-genmo** [comment]
You don't need to. Just run the script, and t5 will automatically be downloaded. However, you still need to manually download the other weights from huggingface, which you can find here: https://huggingface.co/genmo/mochi-1-preview.

**Comment by ptits** [comment]
> Just run the script

which script?

i dont see any download code within this repo\branch

can you point me to the piece of code for downloading? in which .py script?
