### ISSUE TITLE
in windows system user command  uv pip install -e . --no-build-isolation

### ISSUE THREAD

**Issue by shuwihli** [genmoai/models#70]
<img width="1232" alt="微信图片_20241108112713" src="https://github.com/user-attachments/assets/c653bd71-6751-4833-bc7c-998afca29400">

"On the Windows system, I encountered an exception when using the command uv pip install -e . --no-build-isolation. What should I do for help?"

If you need further assistance with the issue you're facing, please provide more details about the exception or error message you received, and I'll do my best to help you resolve it.

**Comment by FurkanGozukara** [comment]
I recommend SwarmUI so easy to use

Here video tutorail

[**How To Use Mochi 1 Open Source Video Generation Model On Your Windows PC, RunPod and Massed Compute**](https://youtu.be/iqBV7bCbDJY)

[![image](https://cdn-uploads.huggingface.co/production/uploads/6345bd89fe134dfd7a0dba40/_n6EeRn1P_HoBhwXhuP_E.png)](https://youtu.be/iqBV7bCbDJY)

**Comment by ved-genmo** [comment]
@shuwihli You need to be in the base directory for this repository (where the `pyproject.toml` file exists).

**Comment by shuwihli** [comment]
Thank you very much, I have successfully downloaded this package

**Comment by shuwihli** [comment]
Thanks for the recommendation, I'll check it out
