### ISSUE TITLE
How to get from z_0 to z_t?

### ISSUE THREAD

**Issue by alebeck** [genmoai/models#83]
Hi,

First of all thanks for your exiting work!

We were trying to reverse-engineer the process of going from a denoised latent code z_0 to its noisy version z_t at some time t, depending on sigma_t. We tried just adding Gaussian noise with standard deviation sigma_t (corresponding to a variance-exploding scheme), however this didn't seem to work. Also from a theoretical perspective, this approach would result in too much residual information from z_0 at time t=T, i.e. a signal to noise ratio >> 0.

Could you point us into the right direction here, for example how you noised the clear latent codes to some noise level during training?

Thanks in advance!

Alex

**Comment by ajayjain** [comment]
Hi Alex,

Mochi is a rectified flow model. Instead of adding Gaussian noise only, you should linearly interpolate z_0 and eps with `z_t = (1 - sigma) * z_0 + sigma * eps`.

Reference: https://arxiv.org/abs/2210.02747

**Comment by alebeck** [comment]
Awesome, thank you! :)
